export const UserActionTypes = {
  TOGGLE_SIGN_IN_SIGN_UP: "TOGGLE_SIGN_IN_SIGN_UP",
  SET_USER_INFO: "SET_USER_INFO",
  SET_USER_PROFILE: "SET_USER_PROFILE",
  RESET_USER_INFO: "RESET_USER_INFO",
  SET_PREMISSION: "SET_PREMISSION",
};
