export const StoresActionTypes = {
  SET_ALL_STORES: "SET_ALL_STORES",
  SET_STORE_PRODUCTS: "SET_STORE_PRODUCTS",
  ADD_STORE: "ADD_STORE",
  REMOVE_STORE: "REMOVE_STORE",
  UPDATE_STORE: "UPDATE_STORE",
};
